package github.com.rhacco.dota2androidapp.sources.repos

object HeroesLocalDataSource {
    private var mHeroNames: Map<Int, String> = mapOf(
            1 to "Anti-Mage",
            2 to "Axe",
            3 to "Bane",
            4 to "Bloodseeker",
            5 to "Crystal Maiden",
            6 to "Drow Ranger",
            7 to "Earthshaker",
            8 to "Juggernaut",
            9 to "Mirana",
            10 to "Morphling",
            11 to "Shadow Fiend",
            12 to "Phantom Lancer",
            13 to "Puck",
            14 to "Pudge",
            15 to "Razor",
            16 to "Sand King",
            17 to "Storm Spirit",
            18 to "Sven",
            19 to "Tiny",
            20 to "Vengeful Spirit",
            21 to "Windranger",
            22 to "Zeus",
            23 to "Kunkka",
            25 to "Lina",
            26 to "Lion",
            27 to "Shadow Shaman",
            28 to "Slardar",
            29 to "Tidehunter",
            30 to "Witch Doctor",
            31 to "Lich",
            32 to "Riki",
            33 to "Enigma",
            34 to "Tinker",
            35 to "Sniper",
            36 to "Necrophos",
            37 to "Warlock",
            38 to "Beastmaster",
            39 to "Queen of Pain",
            40 to "Venomancer",
            41 to "Faceless Void",
            42 to "Wraith King",
            43 to "Death Prophet",
            44 to "Phantom Assassin",
            45 to "Pugna",
            46 to "Templar Assassin",
            47 to "Viper",
            48 to "Luna",
            49 to "Dragon Knight",
            50 to "Dazzle",
            51 to "Clockwerk",
            52 to "Leshrac",
            53 to "Nature's Prophet",
            54 to "Lifestealer",
            55 to "Dark Seer",
            56 to "Clinkz",
            57 to "Omniknight",
            58 to "Enchantress",
            59 to "Huskar",
            60 to "Night Stalker",
            61 to "Broodmother",
            62 to "Bounty Hunter",
            63 to "Weaver",
            64 to "Jakiro",
            65 to "Batrider",
            66 to "Chen",
            67 to "Spectre",
            68 to "Ancient Apparition",
            69 to "Doom",
            70 to "Ursa",
            71 to "Spirit Breaker",
            72 to "Gyrocopter",
            73 to "Alchemist",
            74 to "Invoker",
            75 to "Silencer",
            76 to "Outworld Devourer",
            77 to "Lycan",
            78 to "Brewmaster",
            79 to "Shadow Demon",
            80 to "Lone Druid",
            81 to "Chaos Knight",
            82 to "Meepo",
            83 to "Treant Protector",
            84 to "Ogre Magi",
            85 to "Undying",
            86 to "Rubick",
            87 to "Disruptor",
            88 to "Nyx Assassin",
            89 to "Naga Siren",
            90 to "Keeper of the Light",
            91 to "Io",
            92 to "Visage",
            93 to "Slark",
            94 to "Medusa",
            95 to "Troll Warlord",
            96 to "Centaur Warrunner",
            97 to "Magnus",
            98 to "Timbersaw",
            99 to "Bristleback",
            100 to "Tusk",
            101 to "Skywrath Mage",
            102 to "Abaddon",
            103 to "Elder Titan",
            104 to "Legion Commander",
            105 to "Techies",
            106 to "Ember Spirit",
            107 to "Earth Spirit",
            108 to "Underlord",
            109 to "Terrorblade",
            110 to "Phoenix",
            111 to "Oracle",
            112 to "Winter Wyvern",
            113 to "Arc Warden",
            114 to "Monkey King",
            119 to "Dark Willow",
            120 to "Pangolier")

    fun getNamesByIds(ids: List<Int>): List<String?> {
        val result: MutableList<String?> = mutableListOf()
        ids.forEach { result.add(mHeroNames[it]) }
        return result
    }
}